### PR TITLE
support windows builds

### PR DESCRIPTION
**Pull request by Groutcho**
This PR is a work in progress.

Support windows builds by
- tweaking the top-level `CMakeLists.txt`:
  - locate some libraries using `find_libraries` (lzma, jsoncpp, pdal_util). For simplicity's sake, we assume we will find those libraries in the same tree as PDAL (default is `C:\pdalbin`)
  - disable tests on MSVC (I couldn't compile the test projects)
- fix the known `NOMINMAX` issue on MSVC (see http://stackoverflow.com/q/4913922)
- add some `#include` to appease MSVC

Also, add scripts to prepare for a future AppVeyor automation (inspired by PDAL).

Tested on CMake generator `Visual Studio 14 2015 Win64`.

### CODE REVIEW

**Comment by Groutcho** [comment]
The test not building seem a rather ordinary problem of standard libraries being linked with invalid variants (debug, release, static, shared...)

**Comment by connormanning** [comment]
Looks good.  You mentioned it's a work in progress - what more is needed for full support?

**Comment by Groutcho** [comment]
@connormanning, except for the Arbiter support (mkdirp, remove) on Windows, nothing more is needed. It' s just that this PR needs polishing:
- We shouldn't disable tests on windows
- 6da54ce is weird to me. It works but I don't really know if it's the correct fix.

**Comment by connormanning** [comment]
Automated AppVeyor build has been enabled [here](https://ci.appveyor.com/project/hobu/entwine).

**Comment by Groutcho** [comment]
Do you know how to get to build PDAL before building Entwine using Appveyor ? I pinged @hobu on gitter, but maybe it's better to discuss it here.

We need to build the .lib (`pdal_util.lib`, `pdalcpp.lib`) files to be able to link them to Entwine, but the Appveyor build for PDAL only produces final binaries (exe & dll), so I guess we could rule that out.

Would it be reasonable to produce a nuget package containing those libs ?

**Comment by hobu** [comment]
> We need to build the .lib (pdal_util.lib, pdalcpp.lib) files to be able to link them to Entwine, but the Appveyor build for PDAL only produces final binaries (exe & dll), so I guess we could rule that out.

I am working to have OSGeo4W64 packages of PDAL and libs available in the next few weeks.

**Comment by connormanning** [comment]
Thanks for this contribution - I've merged it as-is since it already seems useful if it gets Windows stuff building.  AppVeyor can be resolved separately.

**Pull request merged**
